version: "3"

services:
  db: 
    image: postgres
    environment:
      POSTGRES_USER: "postgres"    
      POSTGRES_PASSWORD: "gava167943"
      POSTGRES_DB: "generic-store"
    volumes: 
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"

  api: 
    depends_on: 
      - db
    build: .
    command: yarn dev
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
